### ISSUE TITLE
`feedbuilder.py` error

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#91]
I'm getting an error when I try to run `feedbuilder.py`.  I've tried on two computers now, same error.

```
Loading the following files:
[WindowsPath('C:/Users/kkoziar/repos/kek-uc-love-data-week.github.io/_data/yml_2021/workshops.yml'),
 WindowsPath('C:/Users/kkoziar/repos/kek-uc-love-data-week.github.io/_data/yml_2022/workshops.yml'),
 WindowsPath('C:/Users/kkoziar/repos/kek-uc-love-data-week.github.io/_data/yml_2023/workshops.yml'),
 WindowsPath('C:/Users/kkoziar/repos/kek-uc-love-data-week.github.io/_data/yml_2024/workshops.yml')]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 89, in peek
    return self.buffer[self.pointer+index]
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "feedbuilder.py", line 28, in <module>
    yaml_list = yaml.safe_load(f)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\scanner.py", line 1151, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\scanner.py", line 1232, in scan_flow_scalar_spaces
    while self.peek(length) in ' \t':
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 91, in peek
    self.update(index+1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 153, in update
    self.update_raw()
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 275: character maps to <undefined>

**Comment by devnich** [comment]
This appears to be a Windows character encoding issue. There's a lot of blame to go around.

The error is caused by the "Data resources for Social Sciences & social media data ethics" 2024 workshop entry. The description includes the following:

```notion of “Data” concerning social media```

...where Data is surrounded by smart quotes. This loads correctly when the file is parsed as UTF-8. However, if the file is parsed as Windows-1252, it looks like this:

```notion of â€œDataâ€� concerning social media```

...where the blank glyph is the 0x9d character referenced at the end of the error message. This corresponds to Extended ASCII 157, which is undefined in Windows 1252.

So the upshot is that your Python installation is (correctly) using its current locale to load the YAML file and breaking on that character. You try to force it to use UTF-8 as its locale by running the program using:

```python -X utf8 feedbuilder.py```

cf. https://peps.python.org/pep-0540/

Let me know if that works.
